### PR TITLE
Fix branch not to be updated when refreshRate used (#1136)

### PR DESCRIPTION
**Pull request by LukasVyhlidka**
Fixes issue #1136.

### CODE REVIEW

**Comment by LukasVyhlidka** [comment]
I have added an Unit test.

**Comment by LukasVyhlidka** [comment]
So, could we merge that?

**Comment by LukasVyhlidka** [comment]
Thanks. Do you want me to merge that into the master?

**Comment by spencergibb** [comment]
No, we will merge forward.

**Comment by ryanjbaxter** [comment]
@LukasVyhlidka it is now merged into 2.0.x and master

**Comment by LukasVyhlidka** [comment]
Great! :)

**Pull request merged**
