### PR TITLE
Fix typo 'encypt' -> 'encrypt'

### PR DESCRIPTION
**Pull request by davidmorley**

### CODE REVIEW

**Comment by spencergibb** [comment]
@davidmorley have you signed the contributors agreement before?

**Comment by davidmorley** [comment]
@spencergibb, Yes! I have the confirmation number if needed.

**Comment by spencergibb** [comment]
Nope, just needed to know/remember :-)

**Comment by davidmorley** [comment]
Thanks! Loving Spring Cloud (and specifically Spring Cloud Config), and can't wait to see more at SpringOne 2GX. Keep up the great work.

**Pull request merged**
