### PR TITLE
Delete basedir when clone fails (#373)

### PR DESCRIPTION
**Pull request by copa2**
Fixes: #373

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@copa2 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=543)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=543) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by ryanjbaxter** [comment]
I am wondering if the `try/catch` should be in `copyRepository` so if there are any issues copying the repo from the file system we clean that up as well?

**Comment by copa2** [comment]
In my opinion `copyFromLocalRepository` is just opening GIT on the file system. 
So there is no copy to baseDir (as the naming suggest).

**Comment by pivotal-issuemaster** [comment]
@copa2 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=543)!

**Comment by ryanjbaxter** [comment]
OK I agree

**Pull request merged**
