### PR TITLE
Use default label if cloneOnStart is true

### LINKED ISSUE #1609: Cloneonstart flag doesn't checkout the branch mentioned in label
In the cloud config server application.yml, if cloneOnStart is set to true, then default label is ignored and most active branch is checked out.

Spring cloud dependency version: Hoxton.SR4
Spring clould config server version: 2.2.2RELEASE

Sample application.yml

 uri: ${CENTRALIZED_GIT_URI}
 username: ${SERVICE_USERNAME}
 password: ${SERVICE_PASSWORD}
 **cloneOnStart: true
    defaultLabel: qa // This is not read and most active branch is checked out **

Expected Behavior:
The cloneOnStart should consider the defaultLabel so that the expected label is not checked out during first request.

### PR DESCRIPTION
**Pull request by gauravhanda**
Added code to checkout the repository to the defautlLabel when cloneOnStart is true.

Fixes #1609

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gauravhanda Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1610)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1610) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gauravhanda Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1610)!

**Comment by gauravhanda** [comment]
> Can you add a test?

Yes sure. Almost done

**Comment by gauravhanda** [comment]
@spencergibb : Added additional condition to checkout the default label only when default branch set on repository by admin is not same as default label. If they are same, there is no value add in doing a checkout post cloning.
Added following test cases :
1. Checkout of default label should be triggered when defaul label is not null and not same as default branch
2. Checkout of default label shouldn't be triggered when default label is null or same as default branch of repository

**Comment by gauravhanda** [comment]
@spencergibb : Apologies, couldn't figure out the changes requested. Any pointers?

**Comment by spencergibb** [comment]
It was the tests

**Comment by gauravhanda** [comment]
> It was the tests

Any issues? I can't find comments.

**Comment by spencergibb** [comment]
No, simply the fact that I wanted you to add tests

**Comment by gauravhanda** [comment]
I added 2 tests for both happy and negative path. Is there anything specific test you want me to add?

**Comment by gauravhanda** [comment]
@spencergibb  Just wanted to follow up on review comments. Is there something specific you want me to write test case?

**Comment by gauravhanda** [comment]
@spencergibb : Following up to provide me few pointers to that we can close this issue.

**Pull request merged**
