### PR TITLE
Add version to environment response

### PR DESCRIPTION
**Pull request by spencergibb**
fixes gh-244

@dsyer probably my biggest question is how to present the version to boot? Currently I'm adding the version to to the name of the property source on the server. The client isn't using version yet.  What do you think?

```
{
    "configService:https://github.com/spring-cloud-samples/config-repo/application.yml@bdcfc52819cfb29582ebb06f7b970ae6b65e4985": {
        "info.description": "Spring Cloud Samples"
    }
}
```

### CODE REVIEW

**Comment by dsyer** [comment]
I don't like the commit id in the property source name (it might change between fetches). Wouldn't it be better to add it as a field in `Environment`? (Not sure what the client would do with it other than log it.)

**Comment by spencergibb** [comment]
It is in a field in environment. The request was for someone wanting to see what version was retrieved.

**Comment by spencergibb** [comment]
A kind of auditing function.

**Comment by spencergibb** [comment]
If the `EnvironmentEndpoint` could display some metadata about the propertysource besides name, we could put the version there.

**Comment by spencergibb** [comment]
How about this?
```
2015-10-01 15:21:08.416  INFO 3322 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2015-10-01 15:21:09.087  INFO 3322 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Located environment: name=customers, profiles=[default], label=null, version=bdcfc52819cfb29582ebb06f7b970ae6b65e4985
2015-10-01 15:21:09.087  INFO 3322 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource [name='configService', propertySources=[MapPropertySource [name='https://github.com/spring-cloud-samples/config-repo/application.yml']]]
2```

**Pull request closed without merging**
