### PR TITLE
[WIP]Security enhancement.

### PR DESCRIPTION
**Pull request by ian4hu**
Working in progress. Suggestions and discuss are welcomed.

For #1902 #1796 .

As discussed in #1796 .

## Main function
- Use SecurityEnhancer to secure sensitive components accessed by controller/web.
  - SecurityEnhancer to wrap components with *Secure* metadata by `@PreAuthorize` on `EnvRepoWithSecurity` mark interface.
  - Spring Security will invoke `AuthorityExtractor` to extract authorities for a certain access to sensitive component (like `EnvironmentRepository`, `ResourceRepository`, `Encryptor/Decryptor`).
- Use Spring Security to check authorities for requestor/client.

### CODE REVIEW

**Comment by spencergibb** [comment]
This kind of change typically requires some design on our side before making a PR like this. We have prior art in the commercial side that we could base work on. I'm not sure we'll be able to merge this.

**Comment by ian4hu** [comment]
> This kind of change typically requires some design on our side before making a PR like this. We have prior art in the commercial side that we could base work on. I'm not sure we'll be able to merge this.

I made this PR for discussion more likely.

**Comment by spencergibb** [comment]
I appreciate it, but such a large change should be discussed first. Had you done that I would have cautioned you not to do any work yet. We have code (closed source) that we would like to start with that you don't have access to

**Comment by ian4hu** [comment]
will the close sourced solution be.considered to open?

**Pull request closed without merging**
