### PR TITLE
feat: resource charset support

### PR DESCRIPTION
**Pull request by klopfdreh**
Fixes: https://github.com/spring-cloud/spring-cloud-config/issues/2115

Edit: In the web-view git shows the foo_enc.properties in a wrong way. In the IDE however it is encoded as intended. I added a hint in the `.gitattributes` so that `UTF-8` is used. Lets see if the build is working and the fetch is using the proper encoding.

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@klopfdreh could you add some documentation for this?

**Comment by klopfdreh** [comment]
Sure 👍- beside the java doc where do I have to add it?

**Comment by ryanjbaxter** [comment]
Somewhere in here.  Not sure if you think there is a good spot to mention this new feature.  Let me know what you think.  We could add a new page as well.

**Comment by klopfdreh** [comment]
I am going to add some documentation as soon as possible in this ticket.

Main reason for the feature is that if you use other characters not covered by UTF-8 you can configure the client that a given charset is set for requests and the server is reading and delivering the resource with that charset.

**Comment by klopfdreh** [comment]
As I remember from the previous PR I provided 2024 is 4.1.x, so I changed the base of the PR to this branch.

I added some documentation into the ascii doc pages. 

The file `spring-cloud-config-server/src/test/resources/test/dev/foo_enc.properties` is still not shown correctly in the GitHub UI, but the tests are working as expected with `.gitattributes`

Bildschirmfoto 2024-10-04 um 06 09 12

**Comment by ryanjbaxter** [comment]
I want to keep this in main as it is new functionality.

**Comment by klopfdreh** [comment]
Thanks for merging this feature.

**Pull request merged**
