### PR TITLE
pom.xml file cleanup

### PR DESCRIPTION
**Pull request by Buzzardo**
I started by removing the docbkx plugin. Marcin also pointed out that I could remove the mojo plugin and the inherited=false lines, so I did that.

NOTE: This PR depends on https://github.com/spring-cloud/spring-cloud-build/pull/84

DO NOT merge this one until that one is merged.

### CODE REVIEW

**Comment by karateechop** [comment]
Yeah

**Comment by spencergibb** [comment]
@Buzzardo is this still an issue? If so, we'd need to target the 2.2.x branch. Feel free to open a separate PR

**Comment by Buzzardo** [comment]
Yes. We should make this change to keep the projects consistent with one another.

**Comment by spencergibb** [comment]
Things have changed enough that you'll need to see if what we have is good enough on 2.2.x or not.

**Comment by Buzzardo** [comment]
When I go look at the docs pom in 2.2.x, I see that we're OK, so we can let this one go. Thanks.

**Pull request closed without merging**
