### PR TITLE
#1228 - Support If-Modified-Since

### PR DESCRIPTION
**Pull request by rgoers**
Supports If-Modified-Since header and returns Last-Modified header

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rgoers Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1234)!

**Comment by rgoers** [comment]
Updated to use tabs

**Comment by ryanjbaxter** [comment]
Please revert the import order changes.  Also the rest of the formatting changes you made make it hard to actually see the code changes, could you revert the other formatting changes as well?

**Comment by ryanjbaxter** [comment]
I am closing this PR in favor of #1235, we will merger that forward into master once the above concerns are addressed.

**Pull request closed without merging**
