### PR TITLE
Update AwsCodeCommitCredentialProvider.java

### PR DESCRIPTION
**Pull request by tapvirvirk**
Uri must be encoded inside canhandle when instantiating URI object as uri can contains curly braces e.g.
https://git-codecommit.$AWS_REGION.amazonaws.com/v1/repos/$repo-name/{application}

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tapvirvirk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=704)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=704) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by spencergibb** [comment]
How about a test that fails before your change, but is successful with the change.

**Comment by tapvirvirk** [comment]
Git URI: : https://git-codecommit.$REGION.amazonaws.com/v1/repos/{application}
"canHandle" method gives an exception "java.net.URISyntaxException: Illegal character in path at index 56: https://git-codecommit.xxxx.amazonaws.com/v1/repos/{application}"

With the change, canHandle works properly.

Small Program to test: -
try
    {
      final String url = "https://git-codecommit.xxxx.amazonaws.com/v1/repos/{application}";
      //URI uri = new URI (URLEncoder.encode(url,"UTF-8"));
      URI uri = new URI (url);
      System.out.println(uri.getPath());
    } catch (URISyntaxException e)
    {
      e.printStackTrace();
    }

**Comment by spencergibb** [comment]
I meant, add a junit test to a test class

**Comment by tapvirvirk** [comment]
I added 1 Junit test for curly braces. Negative test can be written as Code is fixed.

**Comment by tapvirvirk** [comment]
@spencergibb 
Did you get a chance to look over the changes?

Thanks
Tapvir

**Comment by ryanjbaxter** [comment]
Please fix the spacing (we use tabs). Also you must sign the CLA before we can accept the changes.

**Comment by pivotal-issuemaster** [comment]
@tapvirvirk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=704)!

**Comment by tapvirvirk** [comment]
@ryanjbaxter 
cc: @spencergibb 

I have fixed the spaces on committed files and signed the cla as well. Can you please review and accept the changes?

Thanks
Tapvir

**Comment by tapvirvirk** [comment]
Thanks @ryanjbaxter 
When this change will be merged?

**Comment by tapvirvirk** [comment]
Thanks @ryanjbaxter.
Do you know when will the next release happening in order to refer the new change in our pom.xml?

**Comment by ryanjbaxter** [comment]
I am not sure at the moment.  Keep an eye on Spring Cloud Release milestones https://github.com/spring-cloud/spring-cloud-release/milestones

**Pull request merged**
