### PR TITLE
Inject Environment into ConfigServerHealthIndicator

### PR DESCRIPTION
**Pull request by marcosbarbero**
This PR will fix the issue https://github.com/spring-cloud/spring-cloud-config/issues/456

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@marcosbarbero Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=457)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=457) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@marcosbarbero Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=457)!

**Comment by dsyer** [comment]
I don't think the travis failure has anything to do with you (it's rubbish). Tests pass for me locally.

Any chance of a new test to show the issue?

**Comment by marcosbarbero** [comment]
Sure I'll work on a test case

**Comment by marcosbarbero** [comment]
@dsyer I'm trying to write a test case but I just figured out it may be not necessary.
The biggest change in this commit is in the class `org.springframework.cloud.config.client.ConfigServerHealthIndicator` constructor, where it was:
```
public ConfigServerHealthIndicator(ConfigServicePropertySourceLocator locator) {
        this.env = new AbstractEnvironment() {
        	@Override
        	public String[] getActiveProfiles() {
        		return new String[] {"default"};
        	}
		};
        this.locator = locator;
}
```
and now it is:
```
public ConfigServerHealthIndicator(ConfigServicePropertySourceLocator locator,
			Environment environment) {
         this.environment = environment;
         this.locator = locator;
}
```
The problem here was happening in the method `ConfigClientProperties#override` because of the `AbstractEnvironment` instance on `ConfigServerHealthIndicator` constructor.
All related methods are tested already so I don't think we should test the constructor itself.

Do you have any advice here?

**Comment by dsyer** [comment]
I'm not sure I follow. If the behaviour depends on the value of the `Environment` being used, then surely there is a test for that?

**Comment by marcosbarbero** [comment]
The behavior depends on value in the `Environment`. This commit is adding an `Environment` into the constructor, before that it used the `AbstractEnv`. With that change we can inject the environment in the Bean creation.

The place where the values get lost was in the properties override method, but there's a test for that already and it works fine.

Got that?

I can try to think in a way to test that but the biggest chance here is the constructor, the rest of the flow keeps the same.

**Comment by dsyer** [comment]
OK so all the behaviour changes in the health indicator come from the`ConfigClientProperties` which are already tested. I get it.

**Comment by marcosbarbero** [comment]
Great! :)
It shouldn't be merged before close the PR?

**Comment by marcosbarbero** [comment]
Oops... it was merged

**Pull request closed without merging**
