### PR TITLE
Optionally decrypt secret properties before sending them to the clients

### PR DESCRIPTION
**Pull request by marmanan**
Add the option to disable decryption in the EnvironmentController to let clients manage decryption of the ciphered properties. In this way, secret properties go encrypted from server to client.

### CODE REVIEW

**Comment by dsyer** [comment]
This looks like it might be useful to some people. But I think the code in `EnvironmentController` has changed since you proposed the change. You might need to revise it and add a few null checks.

**Comment by marmanan** [comment]
I only see the encryptor is used once in EnvironmentController and it´s null checked

Line 102
		if (environmentEncryptor != null) {
			environment = environmentEncryptor.decrypt(environment);
		}

**Comment by dsyer** [comment]
Correct. OK thanks. I think I was looking at the implementation of the `EnvironmentEncryptor` itself and seeing a lot of places where a null check might be needed.

**Comment by marmanan** [comment]
Hi Dave, are you planning to add this to 1.0.2?

**Comment by dsyer** [comment]
I think something equivalent will be in master soon. I'm re-designing some of the encryption features.

**Comment by dsyer** [comment]
I couldn't use your code because your repo doesn't exist any more (according to Github). The change is in though (with a slightly different property name).

**Pull request closed without merging**
