### PR TITLE
GH-1337: Add support for using default label when serving binary reso…

### LINKED ISSUE #1337: Add support for using default label when serving binary resources
Currently, when serving plaintext resources, the client has the ability to use the `useDefaultLabel` flags on the request fallback to the default label configured on the config server.

https://github.com/spring-cloud/spring-cloud-config/blob/e872307968d6c9e6120b5feb3f7a4bab2554e12f/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java#L80-L87

A similar ability is lacking when serving binary resources.
https://github.com/spring-cloud/spring-cloud-config/blob/e872307968d6c9e6120b5feb3f7a4bab2554e12f/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/resource/ResourceController.java#L132-L137

### PR DESCRIPTION
**Pull request by Walliee**
…urces

resolves #1337

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Can you submit this against the 2.0.x branch?

**Comment by Walliee** [comment]
> Can you submit this against the 2.0.x branch?

Hey @ryanjbaxter, you mean just against 2.0.x branch or a separate PR against 2.0.x branch cherry-picking these commits?

**Comment by ryanjbaxter** [comment]
If you submit it against the 2.0.x branch we will merge it forward from there

**Comment by Walliee** [comment]
Created PR #1340 against 2.0.x

**Pull request closed without merging**
