### PR TITLE
Making refresh modifier public so that clients can do AOP failover

### PR DESCRIPTION
**Pull request by asarkar**

### CODE REVIEW

**Comment by spencergibb** [comment]
Why do you need to do AOP on `refresh()`? It's only called from one place `getLocations()`, couldn't you do it there?

**Comment by asarkar** [comment]
@spencergibb Not without extending `AbstractScmAccessor`, methods from which are used in `getLocations`.

**Comment by asarkar** [comment]
@spencergibb What does the team think? This is really a trivial change, so if you don't see a problem with it, I'd like to get it merged. It'd help the ambitious clients.

**Comment by spencergibb** [comment]
@asarkar can you explain in more detail why AOP wouldn't work around `getLocations()` while it would around `refresh()`?

**Comment by asarkar** [comment]
It's not that `getLocations` can't be intercepted, that's not hard. The question is what the alternative implementation might be when we don't want to execute the original method.  Currently `getLocations` uses `protected` methods from `AbstractScmAccessor`, thus making it harded to provided an alternative without having another subclass of `AbstractScmAccessor`.
If you have a suggestion for an alternative `getLocations` without subclassing `AbstractScmAccessor`, I can do that.

**Comment by spencergibb** [comment]
I think it would be helpful to step back and see **why** you are trying to do this rather than implementation details. That would help drive how to achieve your purposes.

**Comment by asarkar** [comment]
I believe this https://github.com/spring-cloud/spring-cloud-config/issues/631 answers your question.

**Comment by dendron8** [comment]
@asarkar do you have an example of how you used this to provide failover? did you failover to a native/local repo?

**Pull request merged**
