### PR TITLE
Subversion availability - config server fallback.

### PR DESCRIPTION
**Pull request by sprgn**
Added subversion fallback to working copy of already checked-out repo when/if subversion server becomes unavailable.  Similar functionality already exists with git repository implementation.

Subversion repository functionality similar to the one already created for git (#390)

### CODE REVIEW

**Comment by spencergibb** [comment]
@sprgn any way to add a test for this?

**Comment by sprgn** [comment]
@spencergibb yes, I'll put one together.

**Comment by sprgn** [comment]
@spencergibb tests are done.

**Comment by spencergibb** [comment]
Squashed and merged with a bit of polish via 2670aaaf244501af1f9cd8e083549578a3f65757. Thanks for the doing the tests so quickly!

**Pull request closed without merging**
