### PR TITLE
Adds support for property origin tracking in config server/client.

### PR DESCRIPTION
**Pull request by spencergibb**
Adds a new format if requested using v2 Accept header, otherwise the
format is backwards compatible so older clients will work with new
servers.

fixes gh-866

/cc @twicksell

requires https://github.com/spring-cloud/spring-cloud-commons/pull/583

### CODE REVIEW

**Comment by dsyer** [comment]
It seems like we need this feature, and this looks like a good start, and we clearly have all the data we need. I don't like the format of the JSON though, and it seems like we could maybe even make a more incremental change that didn't require a new media type (or maybe not, but it's worth thinking about). Repeating the file location/name in every property value seems wasteful, and we could use integer fields for the line and column values, to make them more machine readable, and then convert to canonical "Boot" style format in the client.

**Comment by spencergibb** [comment]
I agree we could probably not repeat the location, but I don't think we can go straight to integers. Ints would work for the file based env repos, like git, but wouldn't work for jdbc or vault. Also, git blame info could go on each origin for git.

**Comment by spencergibb** [comment]
@dsyer @ryanjbaxter @OlgaMaciaszek @marcingrzejszczak @TYsewyn I'm reviving this again.

Two options I can see for the format:

1) file not repeated
```
{
    "label": null,
    "name": "foo",
    "profiles": [
        "cloud"
    ],
    "propertySources": [
        {
            "name": "https://github.com/spring-cloud-samples/config-repo/application.yml (document #1)",
            "source": {
                "application.domain": {
                    "origin": "27:11",
                    "value": "${APPLICATION_DOMAIN:cfapps.io}"
                },
                "endpoints.restart": {
                    "origin": "29:12",
                    "value": "enabled"
                }
         }
    ]
}
```

or repeated
```
{
    "label": null,
    "name": "foo",
    "profiles": [
        "cloud"
    ],
    "propertySources": [
        {
            "name": "https://github.com/spring-cloud-samples/config-repo/application.yml (document #1)",
            "source": {
                "application.domain": {
                    "origin": "[https://github.com/spring-cloud-samples/config-repo/application.yml]:27:11",
                    "value": "${APPLICATION_DOMAIN:cfapps.io}"
                },
                "endpoints.restart": {
                    "origin": "[https://github.com/spring-cloud-samples/config-repo/application.yml]:29:12",
                    "value": "enabled"
                }
         }
    ]
}
```

**Comment by spencergibb** [comment]
Once we get the paired down one (I think I prefer it), we could provide different fields for origin, line and column for origins that support it and an opaque string for others.

**Comment by ryanjbaxter** [comment]
+1 to the paired down version

**Comment by TYsewyn** [comment]
I agree on the paired down version, only question that I have now is whether or not we still need to have that ` (document #1)` suffix in the property source its name since we now have the exact location of the property within that file.

**Comment by spencergibb** [comment]
That comes from spring boot actually

**Comment by spencergibb** [comment]
Here's a sample client error message
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'democonfigclient' to com.example.democonfigclient.DemoconfigclientApplication$Config failed:

    Property: democonfigclient.message
    Value: hello from dev profile
    Origin: https://github.com/spring-cloud-samples/config-repo/foo-dev.yml:3:27
    Reason: size must be between 0 and 10
```

**Pull request merged**
