### PR TITLE
Fixed null pointer exception while attempt to decrypt

### PR DESCRIPTION
**Pull request by ramaiahkk**

### CODE REVIEW

**Comment by ramaiahkk** [comment]
this fix is missing in  2.0.x

**Comment by ryanjbaxter** [comment]
So it was fixed in master?  Can you provide the link to the commit?

**Comment by ramaiahkk** [comment]
https://github.com/spring-cloud/spring-cloud-config/pull/1104/commits

> So it was fixed in master? Can you provide the link to the commit?
https://github.com/spring-cloud/spring-cloud-config/pull/1104/commits

**Comment by ryanjbaxter** [comment]
I just cherry picked that commit https://github.com/spring-cloud/spring-cloud-config/commit/e380b83026b3737be7b566cbc88be6dce5e20e3d.

**Pull request closed without merging**
