### PR TITLE
Support for profile specific config data loading

### LINKED ISSUE #1922: ConfigClient not honoring spring.profiles.active from config server
**Describe the bug**
If I use spring-boot-starter-parent = 2.4.8  vs  2.5.2  then I can't read spring.profiles.active from the Config Server's files 
When running with application.properties with a value of `spring.profiles.default=local`  it connects to the config server and reads both properties files:
```
==> src/main/resources/config/config-client-local.properties <==
readProfile=ConfigServerReadActiveProfile-Local

==> src/main/resources/config/config-client.properties <==
readProfile=ConfigServerReadActiveProfile
spring.profiles.active=${readProfile}
```
And the client outputs  
`The following profiles are active: ConfigServerReadActiveProfile-Local`
But if I switch to 2.5.2 (or 2.5.0, 2.5.1) I get 
`No active profile set, falling back to default profiles: local`

Was this an intended change?

**Example**
[config-server-client-active-profile.zip](https://github.com/spring-cloud/spring-cloud-config/files/6728871/config-server-client-active-profile.zip)

Run first the server `mvn spring-boot:run -f config-server/pom.xml`  then the client `mvn spring-boot:run -f config-client/pom.xml`
As packaged you will see the `No active profile set` message,  if you edit the spring-boot-starter-parent version in the root pom and run the client again, you will get the `The following profiles are active` message

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Fixes #1922

Compliments https://github.com/spring-cloud/spring-cloud-commons/pull/1228

### CODE REVIEW

**Review by spencergibb — APPROVED** [review]

**Comment by ryanjbaxter** [comment]
@fragaLY if you have found an but please open a separate issue and provide a sample to reproduce it and I will happily fix the problem

**Comment by VitaliyKulikov** [comment]
> @ryanjbaxter, If the 'property' source doesn't contain "/" and doesn't contain the "." - the name will be "onfigClient" not "configClient".
> 
> Moreover, extractApplicationName throwing the "java.lang.StringIndexOutOfBoundsException: begin 147, end 111, length 162" for case propertySource.getName() == "configserver:Config resource 'file [../configs/location-service/location-service.yml]' via location '../configs/location-service/' (document #0)"
> 
> Well done.

same here

**Comment by ryanjbaxter** [comment]
@VitaliyKulikov can you open a separate issue with a sample that reproduces the problem?

**Comment by VitaliyKulikov** [comment]
@ryanjbaxter u r wlcm ) https://github.com/spring-cloud/spring-cloud-config/issues/2279

**Comment by ryanjbaxter** [comment]
@VitaliyKulikov thanks!

**Pull request merged**
