### PR TITLE
Change default table structure of JDBC backend. Fixes gh-1420

### PR DESCRIPTION
**Pull request by wsy**
Changed DEFAULT_SQL of JDBC backend of Spring Cloud Config Server. Now we're fetching data from column "CONFIG_KEY" and "CONFIG_VALUE" instead of "KEY" and "VALUE" which conflicts with MySQL keywords and MS SQL Server keywords.
Changed spring-cloud-config document with new column names.
In spring-cloud-config, added tips to tell users to use `spring.cloud.config.server.jdbc.sql` configuration to customize their sql statement and/or table structure.
Changed corresponding unit tests to adapt with above changes.

### CODE REVIEW

**Comment by spencergibb** [comment]
@dsyer thoughts? My concern is a breaking change for dbs where this isn't a problem.

**Comment by dsyer** [comment]
We can't really change the default, I agree. Making it configurable is an option. I think there are already setters for the queries? Maybe just document it? Maybe add an `EnvironmentPostProcessor`?

**Comment by spencergibb** [comment]
Already configurable: `spring.cloud.config.server.jdbc.sql`, so maybe just document.

**Comment by spencergibb** [comment]
@wsy are you willing to rework this to just documentation?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Pull request closed without merging**
