### PR TITLE
add randomize option to randomly select which config server instance …

### PR DESCRIPTION
**Pull request by jeffnelson**
…to use from discovery.

When starting up many microservices all at once (a full stack), we need some kind of load balancing of which config server is used

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jeffnelson Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=564)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=564) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jeffnelson Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=564)!

**Comment by spencergibb** [comment]
This starts to overlap with using ribbon here instead.

**Comment by jeffnelson** [comment]
Is there an out of the box way to use ribbon and consul? I knew there was a way to use ribbon and eureka.

**Comment by spencergibb** [comment]
yes, consul works with ribbon.

**Comment by jeffnelson** [comment]
My apologies. I will look to go that route

**Comment by jeffnelson** [comment]
@spencergibb I am finally getting back to this. So far I have been unable to find any examples showing consul discovery of config server working with ribbon. I also am having trouble finding whatever class would enable such behavior. Could you point me in the right direction?

**Comment by jeffnelson** [comment]
@spencergibb  Reopening this as I have not seen an answer to my questions regarding how to enable ribbon when discovering config server

**Comment by jeffnelson** [comment]
Posted my [question to stackoverflow](http://stackoverflow.com/questions/41124475/ribbon-load-balancer-for-discovery-of-spring-config-server-via-consul) as well

**Comment by spencergibb** [comment]
@jeffnelson there isn't an option to use ribbon, that's what you would need to build.

**Pull request closed without merging**
