### PR TITLE
Initial implementation to support multiple labels in SVN and Git EnvironmentRepos

### PR DESCRIPTION
**Pull request by ryanjbaxter**

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@kvmw here is an initial implementation for SCM repositories.  Let me know what you think

**Comment by kvmw** [comment]
I've tried this locally and it is not returning back the property sources I was expecting.  

I believe the `findOne` method should be called for each individual repo, rather than once for the composite repo. Because locations have overlap in different branches, with the current approach, we are able to search the locations of last `git fetch`.

**Comment by ryanjbaxter** [comment]
@kvmw you are right.  It works fine for SVN because it uses different directories for branches but git does not.  I removed the use of composite, let me know if that works as you expect

**Comment by kvmw** [comment]
@ryanjbaxter  Yes, it is working as expected with my sample configs.

**Pull request merged**
