### PR TITLE
Allow config server to bootstrap resources implements #1729

### PR DESCRIPTION
**Pull request by rolaca11**
implements #1729

### CODE REVIEW

**Comment by spencergibb** [comment]
Hmm... I'm unsure about an implementation as such. Marking for team discussion.

**Comment by rolaca11** [comment]
I'm not 100% confident either. Maybe this is a too special solution for this one case only.

Which part are you not sure about?

**Comment by spencergibb** [comment]
This exactly:
> Maybe this is a too special solution for this one case only.

**Comment by rolaca11** [comment]
How could we extend it?

Do you think introducing a `resource:/[resource-from-server]` be a better solution? It could be introduced in the client side either for requesting resources from the config server

**Comment by spencergibb** [comment]
After discussion with the team, this is too specific, though the premise is good. We would need something more specific. It might require some design on our side first.

**Pull request closed without merging**
