### PR TITLE
Fixed issue on ConfigServerHealthIndicator on client side.

### PR DESCRIPTION
**Pull request by seno5979**
Spring Cloud should not try to connect to default repo on startup.

### CODE REVIEW

**Comment by seno5979** [comment]
This is to fixed issue mentioned below :
https://github.com/spring-cloud/spring-cloud-config/issues/104

**Comment by spencergibb** [comment]
So #104 has been closed since March 2015. Also, your change specifically reverts and breaks #69.

**Comment by seno5979** [comment]
But we still got issue on configServer health indicator on client side.  Seems like with the current code it will try to request 'default' application on config server which is not available:

https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerHealthIndicator.java#L25

**Comment by spencergibb** [comment]
That's the `default` profile, not application. What problem are you having?

**Comment by seno5979** [comment]
My application health page always show below on config-server section :

```
"configServer": {
"status": "UNKNOWN",
"error": "no property sources located"
},
```
The console log display as ;
```
ERROR org.springframework.cloud.config.client.ConfigServicePropertySourceLocator - Could not locate PropertySource: 403 Forbidden
```

After did a little investigation, seems like it requesting the 'default' application name instead of my real application name to config server.

I suspect that the code on below made the configserverhealthindicator override the existing environment and made it uable to resolve spring application name (default value was returned) :
https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerHealthIndicator.java#L25

```
new AbstractEnvironment() {
        	@Override
        	public String[] getActiveProfiles() {
        		return new String[] {"default"};
        	}
		};
```

Note :We have enabled authentication on config server side

**Comment by spencergibb** [comment]
> Note :We have enabled authentication on config server side

and you're getting a 403, which makes sense.

Like I said, as is, this change will make another issue regress, so I won't merge it as is.

**Comment by seno5979** [comment]
But even though I disable the security on config-server, I will still got 404, cause the healthindicator on client side requested the wrong application name.

Is this issue have a fixed already ?

**Comment by seno5979** [comment]
Btw what is the purpose of having new AbstractEnvironment on:

https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerHealthIndicator.java#L25

Why we cannot autowire the already existing environment ?

**Comment by spencergibb** [comment]
@seno5979 I've linked to the reason already #69.  You're issue is not #104, it appears to be something we haven't seen before.

**Comment by seno5979** [comment]
What I experiencing is exactly the same as discussed on #104.

I'm not sure why it being closed while the issue still persist.
I'm fine closing my pull request, but still would like to know how the issue need to be taken care.

**Comment by spencergibb** [comment]
#104 has a similar symptom. The problem was raised on the config server itself, not a client. Please open a new issue.

**Comment by seno5979** [comment]
Maybe #106 is talking the spring-cloud-config client issue. But the same, the status is close while the issue still persist.

**Pull request closed without merging**
