### PR TITLE
Improve logging of JGit exceptions

### PR DESCRIPTION
**Pull request by skhome**
This pull request is suggestion related to Issue #364 (https://github.com/spring-cloud/spring-cloud-config/issues/364)

In some situations the JGit library can fail to update the local Git repository.
While the config server should gracefully handle these situations some added
information from the root cause might be helpful to pinpoint why changes in the
remote repository do not get reflected in the REST API.

### CODE REVIEW

**Comment by dsyer** [comment]
In #364 I suggested DEBUG level. Can we go with that for the multi-repo try/catch?

**Comment by spencergibb** [comment]
ping @skhome

**Comment by skhome** [comment]
I have made the change to the log level. Any additional comments on this PR?

**Comment by spencergibb** [comment]
@dsyer do you want both `debug` in `MultipleJGitEnvironmentRepository`?

**Comment by dsyer** [comment]
Yes, please, both logs have to be the same level. They should be protected with `if(logger.isDebugEnabled())` as well.

**Comment by skhome** [comment]
Sorry, I am confused. I only aded one log statement in `MultipleJGitEnvironmentRepository`, the other one was already there and on `info` level.
Why do you you want to hide even more information that is needed for trouble shooting?

**Comment by dsyer** [comment]
It's better to hide it IMO because it's normal for repositories not to contain any given file you ask them for. I couldn't see any difference between the two log statements from that point of view. Maybe I was wrong?

**Comment by skhome** [comment]
Hmm, I seem to be not qualified for this kind of pull request. I was talking the whole time about exceptions coming from the underlying JGit library. Cases where JGit simply leaves corrupted Git repositories and the config server is unable to recover from this situation itself.

I have no idea what you mean with "it's normal for repositories not to contain any given file you ask them for" in the context of exception handling.

Currently in our setup with an in-house hosted BitBucket server backend the config server behaves in some non-deterministic fashion (not serving new commits, not recognizing new or deleted tags, sometimes recognizing new commits only on the 2nd request). In this state I can not use it for a production environment.

Hiding the exceptions does not help me in any way to trouble shoot what is causing this.

I rest my case, since this goes into the opposite direction as was my intention.

**Comment by dsyer** [comment]
I don't understand why you don't want logging if you have a problem you need to diagnose. Do you want to re-submit?

**Comment by spencergibb** [comment]
Closed with some polish via 0dda21df749350234d2b6ba6a5fcce010f3ababf

**Pull request closed without merging**
