### PR TITLE
Use 'trunk' as default label for Subversion repositories

### LINKED ISSUE #107: make default label 'trunk' for svn on server

### PR DESCRIPTION
**Pull request by royclarkson**
This commit adds a new AbstractEnvironmentRepository that includes
a getDefaultLabel() method for all EnvironmentRepository
implementations. The default implementation returns 'master'.
SvnKitEnvironmentRepository overrides this method to return 'trunk'.
ConfigServerMvcConfiguration and ConfigServerBootstrapConfiguration
will utilize labels configured on the client and server before falling
back to the repository's default label.

Resolves #107

### CODE REVIEW

**Comment by dsyer** [comment]
I'm not sure I understand why `AbstractEnvironmentRepository` (or any `EnvironmentRepository` implementation) needs a default label. Isn't the label always passed into the `findOne()` method explicitly? I'd expect the caller to always be responsible for providing the label.

**Comment by royclarkson** [comment]
Considering the labels, "master" and "trunk" are fairly specific to Git and Subversion respectively, it seems reasonable OOD to make those properties of the `EnvironmentRepository` implementations. I considered another `findOne()` method that did not accept a label (to correspond with the same method in the controller). Then it could use the default label from the repository internally. In the end it felt a bit like clutter to add another method though, but maybe that would be a good idea? An alternative route could be to set this in `ConfigServerConfiguration` when the Profile specific settings/beans are applied.

**Comment by dsyer** [comment]
I see. I just hate using base classes for contracts I guess. Maybe we should add the method to the `EnvironmentRepository` interface? Or else the externalization concerns should go in `ConfigServerProperties`. I think I prefer the latter, but without seeing it I'm not sure.

**Comment by spencergibb** [comment]
Deleting `AbstractEnvironmentRepository` and moving `getDefaultLabel()` to `EnvironmentRepository` seems like a good way to go.

**Comment by royclarkson** [comment]
I did add `getDefaultLabel()` to `EnvironmentRepository` since the interface is what is passed around everywhere. So in terms of a contract, it's not reliant on a base class. I didn't really want to add the base class, but the reason I did was to have a single place to define the default label for all repository implementations. Removing `AbstractEnvironmentRepository` would obviously mean adding `getDefaultLabel()` into each repository class. Otherwise, I'm happy to remove it.

**Comment by dsyer** [comment]
Let's remove it then. I'm sure there is no actual "base class" of common shared defaults since the default label is very backend specific.

**Comment by royclarkson** [comment]
ok, will do. thanks.

**Comment by royclarkson** [comment]
Changes have been pushed. I removed `AbstractEnvironmentRepository` as discussed and updated the affected repository implementations.

**Comment by spencergibb** [comment]
:+1:

**Pull request merged**
