### PR TITLE
CF Auth issue with Instance certificate issue expiry for 2.2.x

### PR DESCRIPTION
**Pull request by kamalakarp**
CF Auth issue with Instance certificate issue expiry
https://github.com/spring-cloud/spring-cloud-config/issues/1693

### CODE REVIEW

**Comment by kamalakarp** [comment]
@mp911de - i did the fix in 2.2.x branch as well. Can you please review and approve the same ?

**Comment by kamalakarp** [comment]
@spencergibb - Can you please review and approve the PR ? @mp911de - already reviewed and approved the 3.0.x fix. I'm backporting it to 2.2.x

**Comment by spencergibb** [comment]
We like to merge forward to eliminate uneeded commits. If this is the same, just backported, we can close the one on 3.0.x and merge this one forward.

**Comment by kamalakarp** [comment]
I'll go ahead and close 3.0.x PR and will use this for forward merge.

**Comment by spencergibb** [comment]
@mp911de can you explain a bit for me. In `PcfAuthenticationOptions` it says it "Defaults to a cached instance certificate/key by resolving `CF_INSTANCE_CERT` and `CF_INSTANCE_KEY1 env variables." Why is this PR needed?

```
			if (instanceCertSupplier == null) {
				instanceCertSupplier = new ResourceCredentialSupplier(
						resolveEnvVariable("CF_INSTANCE_CERT")).cached();
			}

			Supplier<String> instanceKeySupplier = this.instanceKeySupplier;
			if (instanceKeySupplier == null) {
				instanceKeySupplier = new ResourceCredentialSupplier(
						resolveEnvVariable("CF_INSTANCE_KEY")).cached();
			}
```

is it because of `cached()`?

**Comment by mp911de** [comment]
> is it because of cached()?

Exactly. That limitation will be gone with Spring Vault 2.4 (Spring Cloud Vault 3.0), see spring-projects/spring-vault#586.

That being said, the PR should go only into a maintenance branch, while upgrading `master` to the new Spring Vault version in October.

**Comment by kamalakarp** [comment]
@spencergibb -  Can you approve the maintenance branch 2.2.x changes ?

**Pull request merged**
