### PR TITLE
Implement plain text decryption. (spring-cloud#865)

### PR DESCRIPTION
**Pull request by sstiglitz**
### What does this PR do?

This implements the feature request made in GH-865. It adds support to decrypt properties being served as plain text through the ResourcesController. Only JSON, YAML, and Properties file extensions are
supported.

### Design considerations.

- On/off of this feature is through setting both `spring.cloud.config.server.encrypt.enabled` (existing setting) and `spring.cloud.config.server.encrypt.plainTextEncrypt` (entirely new setting) to `true`. By default, plainTextEncrypt is `false`. This is to ensure backwards compatibility and not break existing users which may be expecting encrypted values. The dual enable is a little clunky to me, but couldn't think of a better way given existing features. `spring.cloud.config.server.encrypt.enabled` set to `false` is supposed to turn of decryption entirely so a dependency on this setting seemed right to not break the contract. Please let me know your thoughts.

- Notice I say **file extensions** above. Not file types. For example, a file with a ".json" extension is assumed to be JSON. If it's just text, the system will end up throwing an error due to not being able to parse JSON. I figured a proper file type check was unnecessary given the precedent already being set within EnvironmentController and this being a system-to-system application targeted at developers/operations who can be trusted to maintain consistency between file extensions and file types.

- If a file extension is unsupported, but this new feature is enabled, the unencrypted file will be served and WARN log event will trigger. I see-saw'ed over throwing an exception, but that didn't seem right as a person may want decrypted values when supported, but the untouched file when unsupported. I wasn't sure about the log event either as it might fill up log files on a busy server. Doing nothing at all seems like an equally okay option, but please let me know your thoughts.    

- There is a new dependency to handle YAML parsing. It's using a Jackson YAML module. SnakeYml has similar parsing capabilities, but using Jackson offered good code reuse in an environment already using Jackson, so this seemed like a better choice.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sstiglitz Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1417)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1417) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sstiglitz Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1417)!

**Comment by ryanjbaxter** [comment]
@sstiglitz could you update the PR to resolve the merge conflicts?

**Comment by ryanjbaxter** [comment]
ping @sstiglitz

**Comment by ryanjbaxter** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-config/commit/8025d7d17e20f2c1116d056e4ef1b076531a568b

**Pull request closed without merging**
