### PR TITLE
change to package level, since it's used only it tests  fix related t…

### PR DESCRIPTION
**Pull request by avnerstr**
…o issue #1896

### CODE REVIEW

**Comment by avnerstr** [comment]
@ryanjbaxter something looks weird. Suddenly all my builds breaks. Even when I just fork without adding new code.
for example:
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'org.springframework.cloud.config.server.environment.vault.SpringVaultClientConfiguration': Requested bean is currently in creation: Is there an unresolvable circular reference?


any idea? please help !!

**Comment by ryanjbaxter** [comment]
I just realized this change was made in main and not in the 2.2.x branch.  There was a change to the way circular references were detected in Spring Boot that broke us.  I will need to look into that, but its unrelated to this change.

Is there a reason why these changes should be made in the 2.2.x branch?

**Comment by avnerstr** [comment]
@ryanjbaxter - I guess you mean - shouldn't ? 
if that right, I don't see reason why not. It can be merged to all branches. 

What do I need to do in order to make my build work again. Now even clean fork breaks.

**Comment by ryanjbaxter** [comment]
Create a PR against 2.2.x, that branch should be fine.  I will merge it and merge it into main.  There is nothing you can do about making main build until we figure out the circular reference.

**Comment by ryanjbaxter** [comment]
The build is now passing, but I would still suggest we submit this to the 2.2.x. branch

**Comment by avnerstr** [comment]
@ryanjbaxter  I'm working on that right now

**Comment by avnerstr** [comment]
@ryanjbaxter I see that you didn't insert your fix:
Make GitCredentialsProviderFactory a bean.  Fixes #1896 (#1926)  to branch 2.2.x and my fix depends on it.
Can you do it?

**Comment by ryanjbaxter** [comment]
Im sorry im getting my projects/branches confused, submit the pr to the 3.0.x branch.

**Comment by ryanjbaxter** [comment]
Already addressed in https://github.com/spring-cloud/spring-cloud-config/pull/1926

**Pull request closed without merging**
