### PR TITLE
Add option to clone git repositories on startup

### PR DESCRIPTION
**Pull request by alexcorvino**
Current behavior of the server is to clone a git repository on the
first request against it. For products that have SLAs around the 99th
percentile this can be an issue as the first request will take much 
Longer than normal requests. With this change the server will clone
a git repository on startup if the repository’s property cloneOnStart
is set to true. If the property is not set or is explicitly set to
false then the default behavior of the server is preserved.

Unit tests that were added follow this naming convention:

http://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html

### CODE REVIEW

**Comment by dsyer** [comment]
This looks useful. Did you fill out the contributor's agreement (link in README)? Also, we don't use any strict naming conventions for test methods, so please just use something more informal in the future (it's fine for now).

**Comment by alexcorvino** [comment]
No problem on the naming. We've filled out the corporate contributor agreement so we're good to go on that end.

**Comment by dsyer** [comment]
Thanks. One of your fancy test names looks like it changed an existing method and now there's a merge conflict. Can you rebase and re-push please?

**Comment by alexcorvino** [comment]
Rebased and pushed.

**Comment by dsyer** [comment]
Merged. (Actually you didn't rebase you merged, so I had to do some more work to rebase your changes.)

**Comment by alexcorvino** [comment]
Thanks! (And sorry about the merge.)

**Pull request closed without merging**
