### PR TITLE
issue-1434 Fix order of property sources in jdbc backend config server.

### PR DESCRIPTION
**Pull request by VikramAhuja**
issue-1434 Fix order of property sources in jdbc backend config server.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@VikramAhuja Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1436)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1436) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@VikramAhuja Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1436)!

**Comment by spencergibb** [comment]
I'm still not convinced that the native order is right anymore. I would've hoped to hold off making a PR and give me some time to investigate.

**Comment by spencergibb** [comment]
I'm going to close this for now.

**Pull request closed without merging**
