### PR TITLE
feat(#717): clone git submodules

### LINKED ISSUE #717: Option to clone git submodule at start ?
At start of the server, when git repository is clonned,  submoduler are not cloned / updated.

I havent find any option to   send  "--recussive"  option for git clone.  
Does the option exist ?
Do you have a way to clone the submodules ?

### PR DESCRIPTION
**Pull request by Laisky**
clone git repo with all submodules, this can greatly simplifies how to use a global config-repo in many separate child-config-repos.

fixed #717

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Laisky Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1484)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1484) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Laisky Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1484)!

**Comment by spencergibb** [comment]
Can you please add a test?

**Comment by spencergibb** [comment]
ping @Laisky

**Comment by Laisky** [comment]
@spencergibb sorry, I'm too busy to work on this, my baby just born, and my wife just get over of ICU🙀, and there are a lot of works wait to do. I may return on this after a long time, or maybe you can help to add some tests if you can🙏.

**Comment by pkoli** [comment]
@Laisky - Can I add the test cases of you don't mind?

**Comment by Laisky** [comment]
@pkoli I'm grateful if you can help to finish that.

**Comment by mkkeffeler** [comment]
yes, this would be awesome. can we help get this merged?

**Comment by nhogan5** [comment]
I have forever been perplexed by the fact that multiple repos were not supported by default! Thank you! Lets get this across the finish line!

**Pull request closed without merging**
