### PR TITLE
Exact match of branch names in JGitEnvironmentRepository - Fixes gh-2133

### PR DESCRIPTION
**Pull request by woshikid**
As @ojecborec described in #2133 
> 1. Given
> branch=feature/foo
> tag=foo
>
> 2. Send following request to Config Server
> `/application/default/foo`
>
> 3. `JGitEnvironmentRepository.containsBranch` returns true because `refs/remotes/origin/feature/foo` ends with `/foo`
>
> 4. `checkout.call()`, line 468 throws `RefNotFoundException`. Ref origin/foo cannot be resolved. Which is true as this branch does not exist.

The method `containsBranch` in class `JGitEnvironmentRepository` do have bug dealing with branch name contains slashes (/).

I think it's ok to change the `endsWith` method into `equals` when matching branch names. And this fix the problem.

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Can you add a test that covers the breaking case?

**Comment by woshikid** [comment]
OK, I have added a test that checkout tag `foo` when exists branch `feature/foo`

**Review by ryanjbaxter — CHANGES_REQUESTED** [review]
looks good, can you remove the hooks and info directory?

**Comment by woshikid** [comment]
OK the git directory has been cleaned.

**Pull request merged**
