### PR TITLE
Added /encrypt/validate endpoint

### PR DESCRIPTION
**Pull request by mlueders**
We've had a number of instances where someone has checked in an encrypted value which ended up being incorrect (wrong key, character accidentally deleted before commit, etc).  We've added this endpoint to our config server which allows us to run validation checks on config repo commit.

I figured if we ran into this issue, other people may as well, so figured I'd raise a PR.  If the functionality is something y'all would like to add but in a different form, let me know.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mlueders Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=532)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=532) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mlueders Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=532)!

**Comment by ryanjbaxter** [comment]
This seems useful to me.  We would want to add documentation about the endpoint.

@dsyer @spencergibb what do you think?

**Comment by spencergibb** [comment]
Seems a bit redundant to me. Would just calling decrypt do the same thing?

**Comment by Blackbaud-MikeLueders** [comment]
@spencergibb yes and no.  It would have the same affect but it would also return the decrypted value to the client.  I want to open this endpoint up on the production config server such that it can be called from a jenkins build which can be run to validate whether the configuration is valid, after any change to the config repository.  A proxy prevents decrypt from being called from our build environment.

Does this use case make sense?

Also, once I get confirmation this is something y'all would want to add, I'll update the PR with endpoint documentation.

**Comment by spencergibb** [comment]
OK, makes sense. Why the two different usernames?

**Comment by Blackbaud-MikeLueders** [comment]
Ah, didn't realize - this is my work account, other is personal.  Largely depends on what time of day I'm doing things :)

**Comment by Blackbaud-MikeLueders** [comment]
I'll work on getting documentation added in the next day or two

**Comment by spencergibb** [comment]
ping @mlueders on docs

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.

**Pull request closed without merging**
