### PR TITLE
Adding new test ServerMyTestApplicationTests to show the behavior of spring.config.import added in application.yml vs set as -Dspring.config.import

### PR DESCRIPTION
**Pull request by nagsuchandra**
Difference in behavior with spring.config.import added in application.yml vs set as -Dspring.config.import

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@nagsuchandra Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1839)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1839) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@nagsuchandra Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1839)!

**Comment by spencergibb** [comment]
Can you describe why you have added this?

**Comment by nagsuchandra** [comment]
@spencergibb I added the test to show the issue . application.yml have spring.config.import set in there changes the behavior than when we set it as -Dspring.config.import .

**Comment by spencergibb** [comment]
Ok. You could've done that in a personal repo. The behavior is out of spring cloud's ability to control since that is decided by spring boot. What are your expectations with this PR?

**Comment by nagsuchandra** [comment]
> Ok. You could've done that in a personal repo. The behavior is out of spring cloud's ability to control since that is decided by spring boot. What are your expectations with this PR?

Ok . .Don't merge the PR .. I will leave it  in my  repo only.
However the issue is more visible when spring config server is in the picture, hence I added the test under spring-cloud-config-sample's test cases.

**Comment by spencergibb** [comment]
So the point of this was pointing out the difference in behavior? I'm really trying to understand motivation beyond the sample.

**Comment by nagsuchandra** [comment]
> So the point of this was pointing out the difference in behavior? I'm really trying to understand motivation beyond the sample.

The point was to show difference in behavior - yes that is right . 
And that difference in behavior is actually breaking some of the applications in our environment and as a workaround, we had to set spring.config.use-legacy-processing to true for the time being. 

You mentioned earlier that it is an issue of spring boot , however the issue creates an impact in the context of config server and ordering of properties gets messed up ( please see the details of the issue for further clarity). 
If -Dspring.config.import is provided, the properties defined in remote config repo have higher precedence . 
However if spring.config.import is added in application.yml of the app, the properties defined in remote config repo no longer maintain the higher precedence. 

Are you suggesting that there is no fix that can be added from spring cloud side  ? IMO the issue falls in the middle of spring boot and spring cloud config .

**Comment by spencergibb** [comment]
Closing and moving conversation to #1838

**Pull request closed without merging**
