### PR TITLE
Make fetching of config server from Eureka retryable, add support for failfast

### PR DESCRIPTION
**Pull request by Aloren**
I would like to write functional tests for this feature, but haven't found where to put them. Could you please point where they are? Thanks

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Aloren Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=659)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=659) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Aloren Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=659)!

**Comment by ryanjbaxter** [comment]
Why not put the tests in `DiscoveryClientConfigServiceBootstrapConfigurationTests`?

**Comment by Aloren** [comment]
@ryanjbaxter if unit tests will be ok, I will add. Thanks!

**Comment by Aloren** [comment]
Added tests. Please check if everything is ok. Thanks.

**Comment by ryanjbaxter** [comment]
@spencergibb I was thinking the same thing, but after looking at the existing spring retry integration for connecting to the server it does the same thing.  I didnt have a chance to dig into it yet.

**Comment by Aloren** [comment]
@spencergibb Yes, because I'm only using annotation `@Retryable` from spring-retry. `@Retryable` has runtime retention, it does not have to be present on the classpath.
If it is not on classpath the code will work as earlier without retrying.

**Comment by Aloren** [comment]
@spencergibb @ryanjbaxter are there any other changes that I need to implement? Thanks

**Comment by ryanjbaxter** [comment]
Could you maybe add a test that veifies the behavior when spring-retry is not on the classpath?  Something similar to https://github.com/spring-cloud/spring-cloud-netflix/blob/0abf69dc1d9d1349918e74c1ea8188f42372c9c6/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/ribbon/SpringRetryDisabledTests.java

**Comment by Aloren** [comment]
@ryanjbaxter Thanks for pointing me to the nice feature I was not aware of. (@ClassPathExclusions) I added tests for the case when spring-retry is not on classpath and also refactored existing cases on this configuration so that they were more readable (hope, you'll like it :) ).

**Pull request merged**
