### PR TITLE
Support multiple labels in NativeEnvironmentRepository

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Related to #2449

### CODE REVIEW

**Comment by spencergibb** [comment]
Maybe for main?

**Comment by kvmw** [comment]
@spencergibb 

Is the change in this PR is just for this particular repository or it supposed to be implemented by all other repositories?  I am thinking about JGitEnvironmentRepository and other similar repos. I don't think supporting multiple labels would be easy for JGitEnvironmentRepository
.

**Comment by ryanjbaxter** [comment]
I am curious why you think it would not be easy for JGitEnvironmentRepository?

**Comment by ryanjbaxter** [comment]
I guess I see why now since a label corresponds to a branch and we can only checkout and use a single branch at a time

**Comment by kvmw** [comment]
yes, And It uses NativeEnvironmentRepository via [AbstractScmEnvironmentRepository](https://github.com/spring-cloud/spring-cloud-config/blob/d99423830a796b7c13c9d2d764f8c88fd2925095/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/AbstractScmEnvironmentRepository.java#L59) internally. 

So I supposed we need to split the label and for each entry we have to run what is currently in `AbstractScmEnvironmentRepository::findOne`. 

Something like: 
```java

var labels = label.split(",");
for (String lbl : labels) {
                NativeEnvironmentRepository delegate = new NativeEnvironmentRepository(getEnvironment(),
				new NativeEnvironmentProperties(), this.observationRegistry);
		Locations locations = getLocations(application, profile, lbl);
		delegate.setSearchLocations(locations.getLocations());
		Environment result = delegate.findOne(application, profile, "", includeOrigin);
		result.setVersion(locations.getVersion());
		result.setLabel(lbl);
}
```

I am just worried about the impact of such a change. Maybe I am just being oversuspicious.

**Pull request merged**
