### PR TITLE
Make SQL Without Profile Optional

### LINKED ISSUE #2185: Upgrading to Spring Cloud version 2021.0.5 breaks Config Server with JDBC backend (Oracle)
When upgrading to Spring Cloud version 2021.0.5 from 2021.0.4 Cloud Config Server with JDBC backend (Oracle) stops working. The following error message is thrown:
```
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT "KEY", "VALUE" from PROPERTIES where APPLICATION=? and PROFILE is null and LABEL=?]; nested exception is java.sql.SQLSyntaxErrorException: ORA-00904: "KEY": invalid identifier
```
The only change made is changing the version number in the pom.xml `<spring-cloud.version>2021.0.5</spring-cloud.version>`.

The application.yaml looks like this:
```
spring:
  application:
    name: configserver
  profiles:
    active: jdbc
  datasource:
    url: jdbc:oracle:thin:@connString
    username: user
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      sql-for-validate-connection: select * from dual
      connection-pool-name: cserverConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT PROP_KEY, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 1

# management:
#  endpoints:
#    web:
#      exposure:
#        include: 
#           - refresh

server:
  port: 8080
```

The DDL for the properties table looks like this:
```
CREATE TABLE CONFIGSERVER.PROPERTIES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 CACHE 20 ) ,
    APPLICATION VARCHAR2 (4000) ,
    PROFILE     VARCHAR2 (4000) ,
    LABEL       VARCHAR2 (4000) ,
    PROP_KEY    VARCHAR2 (4000) NOT NULL,
    VALUE       CLOB NOT NULL,
    CREATED_ON  TIMESTAMP DEFAULT SYSDATE NOT NULL,
    CREATED_BY  VARCHAR2 (100) DEFAULT COALESCE(
        REGEXP_SUBSTR(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),'^[^:]*'),
        SYS_CONTEXT('USERENV','SESSION_USER')) NOT NULL,
    UPDATED_ON  TIMESTAMP ,
    UPDATED_BY  VARCHAR2 (100)
) LOGGING;

ALTER TABLE CONFIGSERVER.PROPERTIES
    ADD CONSTRAINT PROPERTIES_PK PRIMARY KEY ( ID )
        USING INDEX LOGGING ;
```
The pom.xml file looks like this:
```<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>oracle.ebaas.cserver</groupId>
    <artifactId>ConfigServer</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>ConfigServer</name>
    <description>ConfigServer</description>
    <properties>
        <java.version>17</java.version>
        <spring-cloud.version>2021.0.5</spring-cloud.version>
        <oracle.jdbc.version>21.7.0.0</oracle.jdbc.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>

        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>${oracle.jdbc.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ucp</artifactId>
            <version>${oracle.jdbc.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Fixes #2185

### CODE REVIEW

**Review by spencergibb — APPROVED** [review]

**Comment by woshikid** [comment]
@ryanjbaxter 
I'm sorry for this issue that I didn't make it optional at first place.
I have read the PR and found some logic maybe wrong.
image
the `enableSqlWithoutProfile` condition should take place in the `else` part.

And as we discussed in #2163 
> when profile dev is specified, no default profile is returned.

the code below may break this rule.
```java
		if (!enableSqlWithoutProfie && !profile.startsWith("default")) {
			profile = "default," + profile;
		}
```

should I create another PR to fix this?

**Comment by ryanjbaxter** [comment]
Thanks for pointing out that bug in my logic.  This change should fix that https://github.com/spring-cloud/spring-cloud-config/commit/0ffbda6d1dfab6e924df4bb145858bed3a93e212

As far as this change goes
```
if (!enableSqlWithoutProfie && !profile.startsWith("default")) {
			profile = "default," + profile;
		}
```
Its basically to retain the functionality that was present before your change, hence why it only takes place when `enableSqlWithoutProfile` is `false`

**Comment by ztomic** [comment]
```this.enableSqlWithoutProfie = properties.isEnableSqlWithoutProfile();``` - missing small letter **l** in field name in repository class

**Comment by ryanjbaxter** [comment]
@ztomic thanks!

**Comment by woshikid** [comment]
https://github.com/spring-cloud/spring-cloud-config/blob/ab3f9f229c13a6d5ed6548fe56cc66781b8399b2/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentRepository.java#L132

`enableSqlWithoutProfie` on the right of `||` is implied to be true, so it can be omitted.
```java
if (!enableSqlWithoutProfie || profile != null) {
```
furthermore, when enableSqlWithoutProfie = false, profile should not be null, so `!enableSqlWithoutProfie` on the left also can be omitted.
```java
if (profile != null) {
  // exec sql with profile
} else {
  // exec sql without profile
}
```
the code above will work fine.

**Comment by woshikid** [comment]
Since the method `addPropertySource()` only exec the right sql according to whether `profile` is null or not, we should add a check of `enableSqlWithoutProfie` flag to this code.
https://github.com/spring-cloud/spring-cloud-config/blob/ab3f9f229c13a6d5ed6548fe56cc66781b8399b2/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JdbcEnvironmentRepository.java#L123

```java
if (enableSqlWithoutProfie) addPropertySource(environment, app, null, label);
```
and this will completely disable the common profile feature.

**Comment by ryanjbaxter** [comment]
This is all true but IMO makes it harder to reason about the code

**Comment by woshikid** [comment]
Well, since it won't cause any problem, it's ok not to simplify the code specially. But it will do run into exceptions if we don't add `if (enableSqlWithoutProfie)` before `addPropertySource(environment, app, null, label);`. That line should be skipped when SqlWithoutProfie is not enabled. Or may I create a new PR to try out a new solution where we don't have to introduce a new `enableSqlWithoutProfie` flag and adaptively compatible with existing projects?

**Comment by woshikid** [comment]
I created a new PR #2200 which will deal with `sqlWithoutProfie` adaptively

**Pull request merged**
