### PR TITLE
Add connect timeout support to HttpClientSupport

### PR DESCRIPTION
**Pull request by pivotal-dylan-roberts**
gh-1033

### CODE REVIEW

**Comment by fahimfarookme** [comment]
Also can comment out [this line](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/JGitEnvironmentRepository.java#L596) since it's not being used since we [provide a custom client](https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit.http.apache/src/org/eclipse/jgit/transport/http/apache/HttpClientConnection.java#L132).

**Comment by pivotal-dylan-roberts** [comment]
@fahimfarookme This PR is simply fixing existing functionality that was broken in the previous PR. Please file separate issues for any new feature requests.

**Comment by ryanjbaxter** [comment]
@pivotal-dylan-roberts can we resolve the conflicts?

**Comment by pivotal-dylan-roberts** [comment]
@ryanjbaxter conflicts resolved

**Pull request merged**
