### PR TITLE
Solve a "500 internal error", a ClassCastException

### PR DESCRIPTION
**Pull request by iskradelta**
#1510 and
#1113

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@iskradelta Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1511)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1511) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@iskradelta Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=1511)!

**Comment by iskradelta** [comment]
Hm the test-setup seems broken, it NPEs on this.controller which should have been init()'ed
The same test and code works good where I developed it on, v2.1.5.RELEASE tag. 

There is 2 other test-cases failing, oh well.

**Comment by iskradelta** [comment]
Ah thats better

**Comment by spencergibb** [comment]
Merged and cherry-picked with some polish via 0d100a7080bfe07e322b8686caadb49fe08775d5

**Pull request closed without merging**
