### PR TITLE
AWS S3 configuration documentation lists incorrect properties

### PR DESCRIPTION
**Pull request by hyness**
Fixes gh-2026

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
This is great, thanks for this!  Can you submit this to the 3.0.x branch?  We can then merge it forward.

**Comment by hyness** [comment]
@ryanjbaxter I will try to do this

**Comment by hyness** [comment]
I fixed the PR, but it won't build due to some permission issue trying to restore the Maven cache

**Comment by ryanjbaxter** [comment]
Yeah not sure why that is happening.  Its a documentation change so we can just merge it.

**Pull request merged**
