### PR TITLE
Sharing default application config in CredHub

### PR DESCRIPTION
**Pull request by Albertoimpl**
Always including application as default so that it can be shared across all applications to be consistent with other repository implementations.

Sharing secrets to the application from the default profile.

Updated the docs to reflect the changes

### CODE REVIEW

**Comment by spencergibb** [comment]
@Albertoimpl do you want this in Greenwich? If so, you'll need to target the 2.1.x branch.

**Comment by Albertoimpl** [comment]
Thanks for taking the time to review it @spencergibb!
It would be great to have it in Greenwich.
Do you cherry-pick it to master or should I duplicate the PR?

**Comment by spencergibb** [comment]
If you rebase to 2.1.x and the force push and then change the base branch it should work.

**Comment by spencergibb** [comment]
Closing in favor of #1477

**Pull request closed without merging**
