### PR TITLE
Fix spring.config.import for environment type native

### PR DESCRIPTION
**Pull request by vananiev**
Fixes import
```yaml
spring.config.import:
  - a.yml
  - car/b.yml
```
of car/b.yml for Native environment.

Relates gh-1989

### CODE REVIEW

**Comment by vananiev** [comment]
Ok, I'll add tests

**Comment by ryanjbaxter** [comment]
OK I talked this over with the team and we think the change is fine.  Also if you could make the change related to the `return` statement I mentioned above that would be great.

Also could you submit this against the 3.0.x branch?  We will merge it forward to main.

**Comment by vananiev** [comment]
> Also could you submit this against the 3.0.x branch? We will merge it forward to main.

Ok.

**Comment by vananiev** [comment]
> Yes we should only return if its true and not if false

> Also if you could make the change related to the return statement I mentioned above that would be great.

I do not fully understand what I should do with `return`. Can you clarify it?

**Comment by ryanjbaxter** [comment]
if `!Arrays.stream(locations).map(this::cleanFileLocation).noneMatch(location -> location.startsWith(finalPattern)
								&& !location.substring(finalPattern.length()).contains("/"));` does not return `true` we should not return and continue to iterate through the list.

**Comment by vananiev** [comment]
@ryanjbaxter, all done

**Review by ryanjbaxter — APPROVED** [review]

**Pull request merged**
