### PR TITLE
Adds incompatbility of ecdsa-sha2-nistp256 to doc

### PR DESCRIPTION
**Pull request by dcg**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dcg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=469)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-config&pullRequestId=469) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by marcingrzejszczak** [comment]
LGTM - @spencergibb WDYT?

**Comment by spencergibb** [comment]
Seems ok if @dcg signs the CLA

**Comment by marcingrzejszczak** [comment]
Congrats @dcg on your first(?) contribution to Spring Cloud :D

**Comment by dcg** [comment]
@marcingrzejszczak  thx, yes first contribution ;)

**Pull request merged**
