### PR TITLE
Fix for paths containing spaces.

### PR DESCRIPTION
**Pull request by connil**
Here is a fix for a problem I have with spaces.
The subversion client checks out config files to a folder and if the path contains spaces (ie %20) new File(location).exists() don't work, a label is never found.

### CODE REVIEW

**Comment by spencergibb** [comment]
Nice! How about a test to go along with it?

**Comment by connil** [comment]
Commited a test.

**Comment by dsyer** [comment]
Thanks. Did you fill out the contributor's agreement (link in README)?

**Comment by spencergibb** [comment]
ping @connil

**Comment by connil** [comment]
Sorry for the delay. Who should I enter as Project Lead?

**Comment by dsyer** [comment]
It doesn't matter much - it's just so one of us is notified. Put me down.

**Comment by connil** [comment]
I've filled out the contributor's agreement.

**Comment by spencergibb** [comment]
Squashed and merged via 78d16336435f05cd7718ad658774f9053fe90f26

**Pull request closed without merging**
