### PR TITLE
Add default-label property to Jdbc Repository

### LINKED ISSUE #2165: Jdbc Repository don't try label main
the Git Repository first try label `main` then `master`.
the Jdbc Repository only try label `master`.

### PR DESCRIPTION
**Pull request by woshikid**
Close #2165 
add `defaultLabel` property to `JdbcEnvironmentProperties` as same as `NativeEnvironmentProperties`

### CODE REVIEW

**Review by ryanjbaxter — CHANGES_REQUESTED** [review]
Please add tests and documentation

**Comment by woshikid** [comment]
sorry for the delay

**Review by ryanjbaxter — COMMENTED** [review]
The default label should be `main` as it is with Git.  If there is no default label `main` then we should fall back and try `master` so we don't break anyone.

**Comment by woshikid** [comment]
Yes, that's exactly what I wanted to do in the first place. And you also mentioned
> We try main then master because it was a default for Git repos. That doesn't mean much in terms of JDBC.

this sounds very reasonable, and I checked the design of `File System Backend`:
```java
private String defaultLabel = "master";
```
it uses `master` as default label and also don't have `tryMasterBranch` feature. So... I think maybe we should make JDBC Backend act as same as File System Backend. And this will not break anyone because the `lable` was hardcoded to `master` before.

**Comment by woshikid** [comment]
I mean, the "try main then master feature" should exclusive to Git Backend

**Comment by ryanjbaxter** [comment]
Maybe I was thinking that we could make that breaking change in our 2022 release, however since the release has already been released with `master` and in addition this PR is for 2021 we cannot break functionality, so now we have to try main and then fallback to master.

**Comment by woshikid** [comment]
This PR will not break anything, the label used to be hardcoded to `master` and I just added a new variable `defaultLabel` with value `master`. No logic has been changed and everything will still run smoothly.

**Pull request merged**
